[window]
# Maximized by default (platform-specific)
startup_mode = "Maximized"
decorations = "Buttonless"         # macOS-specific: no close/max/min buttons
dynamic_padding = true
padding = { x = 8, y = 8 }

[font]
# Choose your preferred Nerd Font with icons
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 20.0 
builtin_box_drawing = true

# TokyoNight theme
[colors.primary]
background = "#0f0f0f"
foreground = "#c0caf5"

[colors.normal]
black   = "#0f0f0f"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/bash"
args = ["--login"]
